---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/arwonder
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -Rf * $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -f .htaccess $DEPLOYPATH/ 2>/dev/null || true
